spring:
  redis:
    host: 192.168.129.112
    password: 123456
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.129.112:3306/zzy_transaction?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
  application:
    name: test-test
server:
  port: 8084
logging:
  level:
    com.zzy: debug
