spring:
  redis:
    host: 192.168.129.112
    password: 123456
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.129.112:3306/zzy_transaction?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 200
      minimum-idle: 8
  application:
    name: tcc-order
server:
  port: 8081


logging:
  file:
    path: C:/Users/zhangyang/Desktop/log/dt
  level:
    com.zzy: debug
